### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by facundoolano** [lambdaclass/riak_core_example#7]
- [x] Create three nodes, join them, test basic key value functions.
- [x] run tests in travis
- [x] setup a cron in travis to run periodically
- [x] complete the tests section of the tutorial

**Comment by unbalancedparentheses** [comment]
I think Lasp something like this using travis docker and docker compose:
https://github.com/lasp-lang/lasp/blob/master/.travis.yml
https://github.com/lasp-lang/lasp/blob/master/Makefile
https://github.com/lasp-lang/lasp/blob/master/docker-compose.yml

I should double check

**Comment by facundoolano** [comment]
We should also check if ct_slave works with riak_core. If that's the case I would prefer it for its simplicity (no external dependencies, easier to explain in the tutorial).

I've used it in throttle: https://github.com/lambdaclass/throttle/blob/master/test/throttle_distributed_SUITE.erl#L19-L31

**Comment by unbalancedparentheses** [comment]
Oh cool, i have never used ct slave :)

**Comment by facundoolano** [comment]
Done
